//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Geo.Core.maplink.route {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RouteSoap", Namespace="http://services.maplink.com.br")]
    public partial class Route : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteTotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteTotalsBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteWithAlternativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteSummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMultiRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteWithMapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Route() {
            this.Url = global::Geo.Core.Properties.Settings.Default.Geo_Core_maplink_route_Route;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRouteCompletedEventHandler GetRouteCompleted;
        
        /// <remarks/>
        public event GetRouteTotalsCompletedEventHandler GetRouteTotalsCompleted;
        
        /// <remarks/>
        public event GetRouteTotalsBatchCompletedEventHandler GetRouteTotalsBatchCompleted;
        
        /// <remarks/>
        public event GetRouteWithAlternativesCompletedEventHandler GetRouteWithAlternativesCompleted;
        
        /// <remarks/>
        public event GetRouteSummaryCompletedEventHandler GetRouteSummaryCompleted;
        
        /// <remarks/>
        public event GetRouteDescriptionCompletedEventHandler GetRouteDescriptionCompleted;
        
        /// <remarks/>
        public event GetMultiRouteCompletedEventHandler GetMultiRouteCompleted;
        
        /// <remarks/>
        public event GetRouteWithMapCompletedEventHandler GetRouteWithMapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRoute", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteResponse GetRoute([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetRoute", new object[] {
                        routeStops,
                        routeOptions,
                        token});
            return ((GetRouteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            this.GetRouteAsync(routeStops, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetRouteOperationCompleted == null)) {
                this.GetRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteOperationCompleted);
            }
            this.InvokeAsync("GetRoute", new object[] {
                        routeStops,
                        routeOptions,
                        token}, this.GetRouteOperationCompleted, userState);
        }
        
        private void OnGetRouteOperationCompleted(object arg) {
            if ((this.GetRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteCompleted(this, new GetRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteTotals", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteTotalsResponse GetRouteTotals([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetRouteTotals", new object[] {
                        routeStops,
                        routeOptions,
                        token});
            return ((GetRouteTotalsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteTotalsAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            this.GetRouteTotalsAsync(routeStops, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteTotalsAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetRouteTotalsOperationCompleted == null)) {
                this.GetRouteTotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteTotalsOperationCompleted);
            }
            this.InvokeAsync("GetRouteTotals", new object[] {
                        routeStops,
                        routeOptions,
                        token}, this.GetRouteTotalsOperationCompleted, userState);
        }
        
        private void OnGetRouteTotalsOperationCompleted(object arg) {
            if ((this.GetRouteTotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteTotalsCompleted(this, new GetRouteTotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteTotalsBatch", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteTotalsBatchResponse GetRouteTotalsBatch([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteTotalsBatchRequest[] routeTotalsBatchRequest, string token) {
            object[] results = this.Invoke("GetRouteTotalsBatch", new object[] {
                        routeTotalsBatchRequest,
                        token});
            return ((GetRouteTotalsBatchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteTotalsBatchAsync(RouteTotalsBatchRequest[] routeTotalsBatchRequest, string token) {
            this.GetRouteTotalsBatchAsync(routeTotalsBatchRequest, token, null);
        }
        
        /// <remarks/>
        public void GetRouteTotalsBatchAsync(RouteTotalsBatchRequest[] routeTotalsBatchRequest, string token, object userState) {
            if ((this.GetRouteTotalsBatchOperationCompleted == null)) {
                this.GetRouteTotalsBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteTotalsBatchOperationCompleted);
            }
            this.InvokeAsync("GetRouteTotalsBatch", new object[] {
                        routeTotalsBatchRequest,
                        token}, this.GetRouteTotalsBatchOperationCompleted, userState);
        }
        
        private void OnGetRouteTotalsBatchOperationCompleted(object arg) {
            if ((this.GetRouteTotalsBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteTotalsBatchCompleted(this, new GetRouteTotalsBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteWithAlternatives", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteWithAlternativesResponse GetRouteWithAlternatives([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetRouteWithAlternatives", new object[] {
                        routeStops,
                        routeOptions,
                        token});
            return ((GetRouteWithAlternativesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteWithAlternativesAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            this.GetRouteWithAlternativesAsync(routeStops, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteWithAlternativesAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetRouteWithAlternativesOperationCompleted == null)) {
                this.GetRouteWithAlternativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteWithAlternativesOperationCompleted);
            }
            this.InvokeAsync("GetRouteWithAlternatives", new object[] {
                        routeStops,
                        routeOptions,
                        token}, this.GetRouteWithAlternativesOperationCompleted, userState);
        }
        
        private void OnGetRouteWithAlternativesOperationCompleted(object arg) {
            if ((this.GetRouteWithAlternativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteWithAlternativesCompleted(this, new GetRouteWithAlternativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteSummary", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteSummaryResponse GetRouteSummary([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetRouteSummary", new object[] {
                        routeStops,
                        routeOptions,
                        token});
            return ((GetRouteSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteSummaryAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            this.GetRouteSummaryAsync(routeStops, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteSummaryAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetRouteSummaryOperationCompleted == null)) {
                this.GetRouteSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteSummaryOperationCompleted);
            }
            this.InvokeAsync("GetRouteSummary", new object[] {
                        routeStops,
                        routeOptions,
                        token}, this.GetRouteSummaryOperationCompleted, userState);
        }
        
        private void OnGetRouteSummaryOperationCompleted(object arg) {
            if ((this.GetRouteSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteSummaryCompleted(this, new GetRouteSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteDescription", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteDescriptionResponse GetRouteDescription([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetRouteDescription", new object[] {
                        routeStops,
                        routeOptions,
                        token});
            return ((GetRouteDescriptionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteDescriptionAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token) {
            this.GetRouteDescriptionAsync(routeStops, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteDescriptionAsync(RouteStop[] routeStops, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetRouteDescriptionOperationCompleted == null)) {
                this.GetRouteDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetRouteDescription", new object[] {
                        routeStops,
                        routeOptions,
                        token}, this.GetRouteDescriptionOperationCompleted, userState);
        }
        
        private void OnGetRouteDescriptionOperationCompleted(object arg) {
            if ((this.GetRouteDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteDescriptionCompleted(this, new GetRouteDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetMultiRoute", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetMultiRouteResponse GetMultiRoute([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] MultiRouteRequest[] multiRouteRequests, RouteOptions routeOptions, string token) {
            object[] results = this.Invoke("GetMultiRoute", new object[] {
                        multiRouteRequests,
                        routeOptions,
                        token});
            return ((GetMultiRouteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetMultiRouteAsync(MultiRouteRequest[] multiRouteRequests, RouteOptions routeOptions, string token) {
            this.GetMultiRouteAsync(multiRouteRequests, routeOptions, token, null);
        }
        
        /// <remarks/>
        public void GetMultiRouteAsync(MultiRouteRequest[] multiRouteRequests, RouteOptions routeOptions, string token, object userState) {
            if ((this.GetMultiRouteOperationCompleted == null)) {
                this.GetMultiRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMultiRouteOperationCompleted);
            }
            this.InvokeAsync("GetMultiRoute", new object[] {
                        multiRouteRequests,
                        routeOptions,
                        token}, this.GetMultiRouteOperationCompleted, userState);
        }
        
        private void OnGetMultiRouteOperationCompleted(object arg) {
            if ((this.GetMultiRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMultiRouteCompleted(this, new GetMultiRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.maplink.com.br/GetRouteWithMap", RequestNamespace="http://services.maplink.com.br", ResponseNamespace="http://services.maplink.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRouteWithMapResponse GetRouteWithMap([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] routeStops, RouteOptions routeOptions, MapOptions mapOptions, string token) {
            object[] results = this.Invoke("GetRouteWithMap", new object[] {
                        routeStops,
                        routeOptions,
                        mapOptions,
                        token});
            return ((GetRouteWithMapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteWithMapAsync(RouteStop[] routeStops, RouteOptions routeOptions, MapOptions mapOptions, string token) {
            this.GetRouteWithMapAsync(routeStops, routeOptions, mapOptions, token, null);
        }
        
        /// <remarks/>
        public void GetRouteWithMapAsync(RouteStop[] routeStops, RouteOptions routeOptions, MapOptions mapOptions, string token, object userState) {
            if ((this.GetRouteWithMapOperationCompleted == null)) {
                this.GetRouteWithMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteWithMapOperationCompleted);
            }
            this.InvokeAsync("GetRouteWithMap", new object[] {
                        routeStops,
                        routeOptions,
                        mapOptions,
                        token}, this.GetRouteWithMapOperationCompleted, userState);
        }
        
        private void OnGetRouteWithMapOperationCompleted(object arg) {
            if ((this.GetRouteWithMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteWithMapCompleted(this, new GetRouteWithMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteStop {
        
        private string descriptionField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteWithMapResponse {
        
        private RouteInfo routeInfoField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public RouteInfo routeInfo {
            get {
                return this.routeInfoField;
            }
            set {
                this.routeInfoField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteInfo {
        
        private string routeIdField;
        
        private MapInfo mapInfoField;
        
        private SegmentDescription[] segDescriptionField;
        
        private RouteTotals routeTotalsField;
        
        private RouteSummary[] routeSummaryField;
        
        private RoadType roadTypeField;
        
        /// <remarks/>
        public string routeId {
            get {
                return this.routeIdField;
            }
            set {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] segDescription {
            get {
                return this.segDescriptionField;
            }
            set {
                this.segDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] routeSummary {
            get {
                return this.routeSummaryField;
            }
            set {
                this.routeSummaryField = value;
            }
        }
        
        /// <remarks/>
        public RoadType roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class MapInfo {
        
        private byte[] imageBinariesField;
        
        private Extent extentField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imageBinaries {
            get {
                return this.imageBinariesField;
            }
            set {
                this.imageBinariesField = value;
            }
        }
        
        /// <remarks/>
        public Extent extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class Extent {
        
        private double xMinField;
        
        private double yMinField;
        
        private double xMaxField;
        
        private double yMaxField;
        
        /// <remarks/>
        public double XMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        public double YMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        public double XMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        public double YMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class SegmentDescription {
        
        private string commandField;
        
        private string descriptionField;
        
        private string poiRouteField;
        
        private POIDetails[] poiRouteDetailsField;
        
        private City cityField;
        
        private string tollFeeField;
        
        private TollFeeDetails tollFeeDetailsField;
        
        private string hasPublicTransportationField;
        
        private PublicTransportationDetails[] publicTransportationDetailsField;
        
        private string roadTypeField;
        
        private double distanceField;
        
        private double cumulativeDistanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string poiRoute {
            get {
                return this.poiRouteField;
            }
            set {
                this.poiRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public POIDetails[] poiRouteDetails {
            get {
                return this.poiRouteDetailsField;
            }
            set {
                this.poiRouteDetailsField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string tollFee {
            get {
                return this.tollFeeField;
            }
            set {
                this.tollFeeField = value;
            }
        }
        
        /// <remarks/>
        public TollFeeDetails tollFeeDetails {
            get {
                return this.tollFeeDetailsField;
            }
            set {
                this.tollFeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string hasPublicTransportation {
            get {
                return this.hasPublicTransportationField;
            }
            set {
                this.hasPublicTransportationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PublicTransportationDetails[] publicTransportationDetails {
            get {
                return this.publicTransportationDetailsField;
            }
            set {
                this.publicTransportationDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public double cumulativeDistance {
            get {
                return this.cumulativeDistanceField;
            }
            set {
                this.cumulativeDistanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class POIDetails {
        
        private string clientIdField;
        
        private string nameField;
        
        private string addressInfoField;
        
        private string sourceField;
        
        private string poiTypeField;
        
        private Point pointField;
        
        /// <remarks/>
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string addressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string poiType {
            get {
                return this.poiTypeField;
            }
            set {
                this.poiTypeField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class City {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class TollFeeDetails {
        
        private int idField;
        
        private string nameField;
        
        private string directionField;
        
        private string addressField;
        
        private string concessionField;
        
        private string phoneField;
        
        private string stateField;
        
        private TollFeePrice[] pricesField;
        
        private double pricePerAxleField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string concession {
            get {
                return this.concessionField;
            }
            set {
                this.concessionField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TollFeePrice[] prices {
            get {
                return this.pricesField;
            }
            set {
                this.pricesField = value;
            }
        }
        
        /// <remarks/>
        public double pricePerAxle {
            get {
                return this.pricePerAxleField;
            }
            set {
                this.pricePerAxleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class TollFeePrice {
        
        private int tollFeeCategoryIdField;
        
        private double priceField;
        
        /// <remarks/>
        public int tollFeeCategoryId {
            get {
                return this.tollFeeCategoryIdField;
            }
            set {
                this.tollFeeCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class PublicTransportationDetails {
        
        private string descriptionField;
        
        private string directionField;
        
        private string lineField;
        
        private string detailsField;
        
        private double distanceField;
        
        private string typeField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteTotals {
        
        private double totalDistanceField;
        
        private string totalTimeField;
        
        private double totalFuelUsedField;
        
        private double totaltollFeeCostField;
        
        private double totalfuelCostField;
        
        private double totalCostField;
        
        private double taxiFare1Field;
        
        private double taxiFare2Field;
        
        /// <remarks/>
        public double totalDistance {
            get {
                return this.totalDistanceField;
            }
            set {
                this.totalDistanceField = value;
            }
        }
        
        /// <remarks/>
        public string totalTime {
            get {
                return this.totalTimeField;
            }
            set {
                this.totalTimeField = value;
            }
        }
        
        /// <remarks/>
        public double totalFuelUsed {
            get {
                return this.totalFuelUsedField;
            }
            set {
                this.totalFuelUsedField = value;
            }
        }
        
        /// <remarks/>
        public double totaltollFeeCost {
            get {
                return this.totaltollFeeCostField;
            }
            set {
                this.totaltollFeeCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalfuelCost {
            get {
                return this.totalfuelCostField;
            }
            set {
                this.totalfuelCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare1 {
            get {
                return this.taxiFare1Field;
            }
            set {
                this.taxiFare1Field = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare2 {
            get {
                return this.taxiFare2Field;
            }
            set {
                this.taxiFare2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteSummary {
        
        private string descriptionField;
        
        private double distanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RoadType {
        
        private double twoLaneHighwayField;
        
        private double secondLaneUnderConstructionField;
        
        private double oneLaneRoadwayField;
        
        private double pavingWorkInProgressField;
        
        private double dirtRoadField;
        
        private double roadwayInPoorConditionsField;
        
        private double ferryField;
        
        /// <remarks/>
        public double twoLaneHighway {
            get {
                return this.twoLaneHighwayField;
            }
            set {
                this.twoLaneHighwayField = value;
            }
        }
        
        /// <remarks/>
        public double secondLaneUnderConstruction {
            get {
                return this.secondLaneUnderConstructionField;
            }
            set {
                this.secondLaneUnderConstructionField = value;
            }
        }
        
        /// <remarks/>
        public double oneLaneRoadway {
            get {
                return this.oneLaneRoadwayField;
            }
            set {
                this.oneLaneRoadwayField = value;
            }
        }
        
        /// <remarks/>
        public double pavingWorkInProgress {
            get {
                return this.pavingWorkInProgressField;
            }
            set {
                this.pavingWorkInProgressField = value;
            }
        }
        
        /// <remarks/>
        public double dirtRoad {
            get {
                return this.dirtRoadField;
            }
            set {
                this.dirtRoadField = value;
            }
        }
        
        /// <remarks/>
        public double roadwayInPoorConditions {
            get {
                return this.roadwayInPoorConditionsField;
            }
            set {
                this.roadwayInPoorConditionsField = value;
            }
        }
        
        /// <remarks/>
        public double ferry {
            get {
                return this.ferryField;
            }
            set {
                this.ferryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class OutputInformation {
        
        private string descriptionField;
        
        private OutputInformationCategory categoryField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformationCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public enum OutputInformationCategory {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        TollFee,
        
        /// <remarks/>
        PointOfInterest,
        
        /// <remarks/>
        ExcludedZone,
        
        /// <remarks/>
        RouteSchedule,
        
        /// <remarks/>
        NonAuthorizedRouteBecauseTraffic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class MapSize {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class MapOptions {
        
        private bool scaleBarField;
        
        private MapSize mapSizeField;
        
        /// <remarks/>
        public bool scaleBar {
            get {
                return this.scaleBarField;
            }
            set {
                this.scaleBarField = value;
            }
        }
        
        /// <remarks/>
        public MapSize mapSize {
            get {
                return this.mapSizeField;
            }
            set {
                this.mapSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class SingleRouteTotals {
        
        private RouteStop originField;
        
        private RouteStop destinField;
        
        private RouteTotals routeTotalsField;
        
        private string logRouteIdField;
        
        private MapInfo mapInfoField;
        
        /// <remarks/>
        public RouteStop origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop destin {
            get {
                return this.destinField;
            }
            set {
                this.destinField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        public string logRouteId {
            get {
                return this.logRouteIdField;
            }
            set {
                this.logRouteIdField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo mapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class MultiRoute {
        
        private SingleRouteTotals[] singleRouteTotalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SingleRouteTotals[] singleRouteTotals {
            get {
                return this.singleRouteTotalsField;
            }
            set {
                this.singleRouteTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetMultiRouteResponse {
        
        private MultiRoute multiRouteField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public MultiRoute multiRoute {
            get {
                return this.multiRouteField;
            }
            set {
                this.multiRouteField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class MultiRouteRequest {
        
        private RouteStop originField;
        
        private RouteStop destinationField;
        
        /// <remarks/>
        public RouteStop origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteDescriptionResponse {
        
        private SegmentDescription[] segmentDescriptionsField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] segmentDescriptions {
            get {
                return this.segmentDescriptionsField;
            }
            set {
                this.segmentDescriptionsField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteSummaryResponse {
        
        private RouteSummary[] routeSummariesField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] routeSummaries {
            get {
                return this.routeSummariesField;
            }
            set {
                this.routeSummariesField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class AlternativeRouteInfo {
        
        private RouteInfo mainRouteField;
        
        private RouteInfo[] alternativesField;
        
        /// <remarks/>
        public RouteInfo mainRoute {
            get {
                return this.mainRouteField;
            }
            set {
                this.mainRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteInfo[] alternatives {
            get {
                return this.alternativesField;
            }
            set {
                this.alternativesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteWithAlternativesResponse {
        
        private AlternativeRouteInfo alternativeRouteInfoField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public AlternativeRouteInfo alternativeRouteInfo {
            get {
                return this.alternativeRouteInfoField;
            }
            set {
                this.alternativeRouteInfoField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteTotalsBatchInfo {
        
        private RouteTotalsBatchRequest requestDataField;
        
        private RouteTotals routeTotalsField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public RouteTotalsBatchRequest requestData {
            get {
                return this.requestDataField;
            }
            set {
                this.requestDataField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteTotalsBatchRequest {
        
        private RouteStop originField;
        
        private RouteStop destinationField;
        
        private RouteOptions optionsField;
        
        /// <remarks/>
        public RouteStop origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public RouteOptions options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteOptions {
        
        private string languageField;
        
        private RouteDetails routeDetailsField;
        
        private Vehicle vehicleField;
        
        private RouteLine[] routeLineField;
        
        private long excludedZoneGroupIdField;
        
        private Controls controlsField;
        
        private RouteSchedule routeScheduleField;
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public RouteDetails routeDetails {
            get {
                return this.routeDetailsField;
            }
            set {
                this.routeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteLine[] routeLine {
            get {
                return this.routeLineField;
            }
            set {
                this.routeLineField = value;
            }
        }
        
        /// <remarks/>
        public long excludedZoneGroupId {
            get {
                return this.excludedZoneGroupIdField;
            }
            set {
                this.excludedZoneGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public Controls controls {
            get {
                return this.controlsField;
            }
            set {
                this.controlsField = value;
            }
        }
        
        /// <remarks/>
        public RouteSchedule routeSchedule {
            get {
                return this.routeScheduleField;
            }
            set {
                this.routeScheduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteDetails {
        
        private int descriptionTypeField;
        
        private bool optimizeRouteField;
        
        private string[] poisField;
        
        private string[] barriersField;
        
        private Point[] barrierPointsField;
        
        private bool tollField;
        
        /// <remarks/>
        public int descriptionType {
            get {
                return this.descriptionTypeField;
            }
            set {
                this.descriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool optimizeRoute {
            get {
                return this.optimizeRouteField;
            }
            set {
                this.optimizeRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("poi")]
        public string[] pois {
            get {
                return this.poisField;
            }
            set {
                this.poisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("barrier")]
        public string[] barriers {
            get {
                return this.barriersField;
            }
            set {
                this.barriersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Point[] barrierPoints {
            get {
                return this.barrierPointsField;
            }
            set {
                this.barrierPointsField = value;
            }
        }
        
        /// <remarks/>
        public bool toll {
            get {
                return this.tollField;
            }
            set {
                this.tollField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class Vehicle {
        
        private int tankCapacityField;
        
        private float averageConsumptionField;
        
        private double fuelPriceField;
        
        private int averageSpeedField;
        
        private int tollFeeCategoryIdField;
        
        /// <remarks/>
        public int tankCapacity {
            get {
                return this.tankCapacityField;
            }
            set {
                this.tankCapacityField = value;
            }
        }
        
        /// <remarks/>
        public float averageConsumption {
            get {
                return this.averageConsumptionField;
            }
            set {
                this.averageConsumptionField = value;
            }
        }
        
        /// <remarks/>
        public double fuelPrice {
            get {
                return this.fuelPriceField;
            }
            set {
                this.fuelPriceField = value;
            }
        }
        
        /// <remarks/>
        public int averageSpeed {
            get {
                return this.averageSpeedField;
            }
            set {
                this.averageSpeedField = value;
            }
        }
        
        /// <remarks/>
        public int tollFeeCategoryId {
            get {
                return this.tollFeeCategoryIdField;
            }
            set {
                this.tollFeeCategoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteLine {
        
        private int widthField;
        
        private string rGBField;
        
        private double transparencyField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string RGB {
            get {
                return this.rGBField;
            }
            set {
                this.rGBField = value;
            }
        }
        
        /// <remarks/>
        public double transparency {
            get {
                return this.transparencyField;
            }
            set {
                this.transparencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class Controls {
        
        private string modeField;
        
        private string[] costAdjustmentsField;
        
        private string trafficField;
        
        private string mapField;
        
        private string extensionMapField;
        
        private string routeControlField;
        
        /// <remarks/>
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("costAdjustment")]
        public string[] costAdjustments {
            get {
                return this.costAdjustmentsField;
            }
            set {
                this.costAdjustmentsField = value;
            }
        }
        
        /// <remarks/>
        public string traffic {
            get {
                return this.trafficField;
            }
            set {
                this.trafficField = value;
            }
        }
        
        /// <remarks/>
        public string map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
            }
        }
        
        /// <remarks/>
        public string extensionMap {
            get {
                return this.extensionMapField;
            }
            set {
                this.extensionMapField = value;
            }
        }
        
        /// <remarks/>
        public string routeControl {
            get {
                return this.routeControlField;
            }
            set {
                this.routeControlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class RouteSchedule {
        
        private string scheduleOfField;
        
        private System.DateTime scheduleField;
        
        /// <remarks/>
        public string scheduleOf {
            get {
                return this.scheduleOfField;
            }
            set {
                this.scheduleOfField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteTotalsBatchResponse {
        
        private GetRouteTotalsBatchInfo[] getRouteTotalsBatchInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GetRouteTotalsBatchInfo[] getRouteTotalsBatchInfo {
            get {
                return this.getRouteTotalsBatchInfoField;
            }
            set {
                this.getRouteTotalsBatchInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteTotalsResponse {
        
        private RouteTotals routeTotalsField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.maplink.com.br")]
    public partial class GetRouteResponse {
        
        private RouteInfo routeInfoField;
        
        private OutputInformation[] outputInformationsField;
        
        /// <remarks/>
        public RouteInfo routeInfo {
            get {
                return this.routeInfoField;
            }
            set {
                this.routeInfoField = value;
            }
        }
        
        /// <remarks/>
        public OutputInformation[] outputInformations {
            get {
                return this.outputInformationsField;
            }
            set {
                this.outputInformationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteCompletedEventHandler(object sender, GetRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteTotalsCompletedEventHandler(object sender, GetRouteTotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteTotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteTotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteTotalsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteTotalsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteTotalsBatchCompletedEventHandler(object sender, GetRouteTotalsBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteTotalsBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteTotalsBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteTotalsBatchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteTotalsBatchResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteWithAlternativesCompletedEventHandler(object sender, GetRouteWithAlternativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteWithAlternativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteWithAlternativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteWithAlternativesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteWithAlternativesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteSummaryCompletedEventHandler(object sender, GetRouteSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteDescriptionCompletedEventHandler(object sender, GetRouteDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteDescriptionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteDescriptionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMultiRouteCompletedEventHandler(object sender, GetMultiRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMultiRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMultiRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMultiRouteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMultiRouteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteWithMapCompletedEventHandler(object sender, GetRouteWithMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteWithMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteWithMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRouteWithMapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRouteWithMapResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591